title: <p align="center"> Dhawal Dethe </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/dhawal-dethe-060b841a/">LinkedIn</a> |
  <a href="https://github.com/dhawaldethe">GitHub</a>
  
  <br>   
   Software Professional with 12+ years of experience in software development using Java,Spring boot,Restful Web services,Confluent-Kafka, JPA-Hibernate, JSF, Oracle DB technologies
  <br>
  </p>



theme: jekyll-theme-minimal